# Generated by Django 3.2.8 on 2021-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_subject', models.CharField(blank=True, max_length=50)),
                ('assignment_name', models.CharField(blank=True, max_length=50)),
                ('assignment_description', models.TextField(blank=True)),
                ('assignment_notes', models.TextField(blank=True)),
            ],
        ),
    ]
