# Generated by Django 4.0 on 2021-12-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='zipcode',
            new_name='zipcode',
        ),
    ]
