# Generated by Django 4.0 on 2021-12-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_zip_code_students_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
