# Generated by Django 4.0 on 2021-12-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_account_balance'),
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cohort',
            new_name='Cohorts',
        ),
    ]
